### ISSUE TITLE
Give details about EFI partition

### ISSUE THREAD

**Issue by qadratic** [dortania/OpenCore-Desktop-Guide#39] opened 2020-05-11 08:38 UTC
opencore-efi.html

So where is this efi partition?
should we create one on the usb stick?
There is no EFI partition when creating usb on linux

**Comment by khronokernel** [comment] 2020-05-11 14:08
So the issue is a bit of a mismatch on naming, I didn't write the Linux install and assumed the EFI partition would be named either EFI(default for macOS) or BOOT for MakeInstall based installers. So the EFI is your 200MB OPENCORE partition:
```
run sudo mkfs.vfat -F 32 -n "OPENCORE" /dev/<your 200MB partition block> to format the 200MB partition to FAT32, named OPENCORE
```
Will fix shortly

**Comment by khronokernel** [comment] 2020-05-11 15:50
Fixed in latest: https://github.com/dortania/OpenCore-Desktop-Guide/commit/a1ccad4d00c97cb3d971897aa24cf802e5fe15d9

**Closed by khronokernel** 2020-05-11 15:50 UTC

**Comment by qadratic** [comment] 2020-05-11 16:25
No. 

> So the issue is a bit of a mismatch on naming, I didn't write the Linux install and assumed the EFI partition would be named either EFI(default for macOS) or BOOT for MakeInstall based installers. So the EFI is your 200MB OPENCORE partition:
> 
> ```
> run sudo mkfs.vfat -F 32 -n "OPENCORE" /dev/<your 200MB partition block> to format the 200MB partition to FAT32, named OPENCORE
> ```
> 
> Will fix shortly

No actually, it says there are 2 methods to make usb installer. But after following method 1, nothing much is actually achieved. Its very misleading.

**Comment by khronokernel** [comment] 2020-05-11 16:28
Method 1:
```
4. run sudo mkfs.vfat -F 32 -n "OPENCORE" /dev/<your USB partition block> to format your USB to FAT32 and named OPENCORE
```
Method 2:
```
run sudo mkfs.vfat -F 32 -n "OPENCORE" /dev/<your 200MB partition block> to format the 200MB partition to FAT32, named OPENCORE
```

Not sure what's misleading if both include the steps for the EFI

**Comment by qadratic** [comment] 2020-05-11 16:30
okay so the last step in method 1 is this
now cp or rsync both BaseSystem.dmg and BaseSystem.chunklist into com.apple.recovery.boot folder.
now whats next? there is no efi partition.

**Comment by khronokernel** [comment] 2020-05-11 16:34
The OPENCORE partitions is the EFI partition, method 2 just splits the main and EFI partition while Method 1 keeps everything in 1 partition

**Comment by qadratic** [comment] 2020-05-11 16:42
I believe It should be mentioned.
